### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ddshin** [BIDS-Apps/ndmg#12] opened 2017-06-26 23:41 UTC
Hi  - 
I am using test data downloaded from OpenfMRI repo (accession # ds000009) to run ndmg with. I used the BIDS online validator to confirm that the directory is BIDS compliant (contains DTI and T1, T2 structural).

I am getting a runtime error.. Something about "IndexError: too many indices"

Any ideas? The screenshot of the error is attached.

Thanks!

![screen shot 2017-06-26 at 4 30 17 pm](https://user-images.githubusercontent.com/9951420/27564694-40d28a04-5a8e-11e7-887a-304acd763080.png)

**Comment by gkiar** [comment] 2017-06-27 16:02
Hi @ddshin - thanks for reaching out! I've seen that bug before, though I thought it had been fixed in the latest version, so this is interesting to see... Could you please try re-running with the pipeline version `bids/ndmg:v0.0.49-1-1` and let me know how it goes?

I'm at the open science room today so we can debug and iterate together, if needed 😄

**Comment by ddshin** [comment] 2017-06-27 18:46
Hi @gkiar -
Awesome, thanks. I am now running with "ndmg:v0.0.49-1-1". I will let you know how it goes. I would love to be at the open science room working on this together with you, except I am in San Diego, CA (UCSD CFMRI). Where are you located?

**Comment by gkiar** [comment] 2017-06-27 19:34
Ah - I'm in Montreal these days (McGill/MNI). I'll try to download a subset of the data you mentioned and will dig in to see what may be causing the bug to pop back up.

For what it's worth the bug was originally caused by sessions which have multiple b0 scans within a stack. I know that this was fixed at one point since I've run many datasets with multiple b0 acquisitions, but must have reintroduced it somehow recently if your current attempt doesn't succeed. Either way, I know how to fix so we'll get it resolved in no time 👍

**Comment by ddshin** [comment] 2017-06-27 19:38
Thanks @gkiar! 

I do get the same error with "ndmg:v0.0.49-1-1". Do you think it would be helpful if I send you the data I am using? If so, let me know and I can leave a dropbox link for you.

**Comment by gkiar** [comment] 2017-06-27 19:41
Hey @ddshin - thanks for confirming, it seems I did indeed bork it recently... I'll pop back tomorrow (unfortunately booked the rest of today) and will see where the bug was reintroduced and resolve it. A dropbox link with 1 or 2 representative sessions from your dataset would be greatly appreciated! From my website [gkiar.github.io](https://gkiar.github.io) you can find my email and send me the link there, please. And thank you for patiently working with me!

**Comment by ddshin** [comment] 2017-06-27 22:48
Cool. I sent you an email with a link to the data. Talk soon!

**Comment by chrisgorgo** [comment] 2017-06-28 05:48
You can also upload the data to OpenNeuro.

**Comment by gkiar** [comment] 2017-08-31 16:26
resolved via email - we found an issue in FSL's applywarp function when running on Mac with insufficient resources allocated when using the epireg function. We're digging further into the problem, but the issue here was just a manifestation of FSL + Docker + Mac not playing nicely with one another.

**Closed as completed by gkiar** 2017-08-31 16:26 UTC

**Comment by ddshin** [comment] 2017-08-31 16:34
Thank you, Greg. I would like to add that the problem also applies to
docker instances on Windows platform.

On Aug 31, 2017 9:26 AM, "Greg Kiar" <notifications@github.com> wrote:

resolved vial email - we found an issue in FSL's applywarp function when
running on Mac with insufficient resources allocated when using the epireg
function. We're digging further into the problem, but the issue here was
just a manifestation of FSL + Docker + Mac not playing nicely with one
another.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BIDS-Apps/ndmg/issues/12#issuecomment-326349969>, or mute
the thread
